version: 2
jobs:
  build_docs:
    docker:
      - image: circleci/python:3.6.7-stretch-node
    steps:
      - checkout

      - run:
          name: smoke test node
          command: |
            node --version

      - run:
          name: Install doc dependencies
          command: |
            /python3.6/bin/pip install -U pip setuptools
            /python3.6/bin/pip install -r doc/doc-requirements.txt
            /python3.6/bin/pip install -r requirements.txt

      # Build the docs
      - run:
          name: Build docs to store
          command: |
            cd doc
            make html

      - store_artifacts:
          path: doc/_build/html/
          destination: html

workflows:
  version: 2
  default:
    jobs:
      - build_docs
