name: binderhub
channels:
  - conda-forge
dependencies:
  - python=3.6
  - sphinx
  - kubernetes>=4.*
  - escapism
  - tornado
  - traitlets
  - docker
  - jinja2
  - prometheus_client
  - python-json-logger
  - jupyterhub
  - jsonschema
  - pip:
      - recommonmark
      - sphinx-copybutton
      - alabaster_jupyterhub
